"""Shared default paths for the local collection workflow."""

from __future__ import annotations

from pathlib import Path


DEFAULT_COLLECTION_DIRECTORY = Path("collection")
DEFAULT_CACHE_DIRECTORY_NAME = "cache"
DEFAULT_CACHE_DIRECTORY = DEFAULT_COLLECTION_DIRECTORY / DEFAULT_CACHE_DIRECTORY_NAME
DEFAULT_ENRICHED_MASTER_PATH = DEFAULT_COLLECTION_DIRECTORY / "enriched-collection.csv"
DEFAULT_PROCESSING_CACHE_PATH = DEFAULT_CACHE_DIRECTORY / "processing.cache.json"
DEFAULT_SEEN_TERMS_CACHE_PATH = DEFAULT_CACHE_DIRECTORY / "collected.cache.json"
DEFAULT_PLAYLIST_OUTPUT_DIRECTORY = DEFAULT_COLLECTION_DIRECTORY / "playlists"
DEFAULT_ON_THE_FLY_PLAYLIST_DIRECTORY = DEFAULT_PLAYLIST_OUTPUT_DIRECTORY / "on-the-fly"
DEFAULT_TRACKLIST_CACHE_PATH = DEFAULT_CACHE_DIRECTORY / "playlist-tracks.cache.json"
DEFAULT_SPOTIFY_MATCH_CACHE_PATH = DEFAULT_CACHE_DIRECTORY / "spotify-track-matches.cache.json"
